spring:
  application:
    name: statement

server:
  port: 8082

logging:
  level:
    ru.gudoshnikova.statement: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

deal:
  service:
    url: http://localhost:8081